### ISSUE TITLE
Add contributing.md

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/admin#10]
We should communicate on how to contribute here in a [`Contributing.md`](https://github.com/blog/1184-contributing-guidelines). @fforres Would you mind creating a PR?

I would love to see following things: 
- PR request required (no direct commits except version numbers)
- npm test needs to be run
- Section on "playnice"
- Link to https://github.com/orgs/nodeschool/teams/admin-maintainer for the persons to contact if a release is necessary.

**Comment by fforres** [comment]
PR Sent, See https://github.com/nodeschool/admin/pull/17

I wasn't sure about the writing style/point to be taken into account.
So any comments are welcome

**Comment by martinheidegger** [comment]
Thank you!
