### ISSUE TITLE
Add Travis setup steps

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/admin#14]
Right now running `init` and creating a `chapter.json` ends with the repo being pushed in a clean state. But `travis` is not yet set up to actually lint the chapter. It would be incredibly awesome if that could work automatically as well but if not: at least a good message for the user on how to do that would be good.

**Comment by dinodsaurus** [comment]
could you be a bit more specific about this one @martinheidegger  ?

**Comment by martinheidegger** [comment]
The chapters should have a travis-script up & running that validates the state of the repository. (Reducing user errors). 

Right now `nodeschool-admin init` creates a `.travis.yml` that will lint the repository every time a push happens. However, after init is finished travis is not being setup to actually setup to trigger when something in the repository changes.

There are several options how to deal with it.
1. We could ask travis to support "trigger on all repositories in organization"
2. We could search for a system that automatically triggers builds on all repos with `.yml`
3. We could implement a `on('push', checkIfContainsTravisYml(enableTravis))` in a own server like "github-teams" or through nodeschoolbot
4. We could add a documentation stating that travis needs to be setup to verify.

**Comment by dinodsaurus** [comment]
I would go for the 4. solution, its easiest and it also promotes use of CI services, which is awesome I would say(we need more of that in the js community)

**Comment by martinheidegger** [comment]
I am okay with 4

**Comment by RichardLitt** [comment]
Agreed on 4.

**Comment by dinodsaurus** [comment]
Ok, now how can we check that their travis test passed ?

**Comment by martinheidegger** [comment]
@dinodsaurus We don't _need_ to check that. The travis setup would be solely for the convenience of the chapter maintainer (to make less mistakes)
