### ISSUE TITLE
Add Region to the list output

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/admin#15]
Right now the [list](https://github.com/nodeschool/admin/blob/master/lib/standard/list.js) method only returns a array of chapters but since the [`chapter-designation.js`](https://github.com/nodeschool/admin/blob/master/country_designations.js) file exists it would be good if the area was automatically added to each item in the list.

A PR that fills the json resulting from `list` with an area lookup would be mighty welcome.

**Comment by dinodsaurus** [comment]
hmmm could you give an example ?

**Comment by martinheidegger** [comment]
The current chapter.json contains `region` for reference [link](https://github.com/nodeschool/nodeschool.github.io/blob/source/chapters/Pune.json#L5) Part of [my proposal](https://github.com/nodeschool/organizers/issues/309) is to move the place of the regions to [`one central logic`](https://github.com/nodeschool/admin/blob/master/country_designations.js). The chapter ['spec'](https://github.com/nodeschool/admin/blob/master/lib/util/schema/chapter.js) already doesn't include the region anymore. But that the output of `list` should contain the region (compiled by the central logic): 

```
{
  "osaka": { 
    "region": "Asia", // <--- here
    "location": {
      "name": "Osaka",
      "country": "JP",
      "lat": 34.6937378,
      "lng": 135.5021651
    },
    "twitter": "nodeschoolosa",
    "name": "Osaka",
    "events": {}
  },
}
```

**Comment by martinheidegger** [comment]
PR #31 exists, closing this issue
