### ISSUE TITLE
Organizers lookup doesn't work without a github authorisation

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/admin#18]
It is possible to [pass-in](https://github.com/nodeschool/admin/blob/2cf6aa407d76db4ad973dce50dde044e0d1fb664/bin/nodeschool-admin#L30) authorisation to the access the data on github. It turns out that [github.teamMembers](https://github.com/nodeschool/admin/blob/8d63264b1afe5f17aad0ec6d6dfd6b2c6d408b36/lib/util/github.js#L46) does not return all teams without the authorisation.

**Comment by martinheidegger** [comment]
This should probably be solved through an external server that presents us with the team list. (See https://github.com/nodeschool/admin/issues/6#issuecomment-173758056)

**Comment by martinheidegger** [comment]
Okay, it took some time but now that we have http://team.nodeschool.io/teams.json we can make this publicly available.

**Comment by dinodsaurus** [comment]
nice job! we should close this issue and create a new one. That would be adding teams list to `list` response
