### ISSUE TITLE
Breaking when no country is selected

### ISSUE THREAD

**Issue by fforres** [nodeschool/admin#21]
Making some tests with Santiago (Chile) suggests the country to be Spain.
Not selecting a suggested country breaks the SW.

I'm working on a PR,  planning on modifying [country_designation.js](https://github.com/nodeschool/admin/blob/master/country_designations.js). 

Keeping the country code as the key, was looking into changing from.

```
[...
'AG',
'AR'
...]
```

to something like this

```
[...
'AG': {
    name: 'Antigua and Barguda'
}, 
'AR':{
    name: 'Argentina'
}
...]
```

**Comment by martinheidegger** [comment]
To me those two look identical.

**Comment by fforres** [comment]
@martinheidegger you are way too fast, just fixed it

**Comment by martinheidegger** [comment]
The chapter.json [requires](https://github.com/nodeschool/admin/blob/432f210a8261f80243e70fb3b9b98d575ce76805/lib/util/schema/chapter.js#L2) the country to be an iso country. The country that is noted in the list should be directly match-able to the area.

```
countryDesignations.byCountry(chapter.location.country)
```

Extended: Not sure why we would need the name for the lookup [`geocode.country`](https://github.com/nodeschool/admin/blob/432f210a8261f80243e70fb3b9b98d575ce76805/lib/util/geocode.js#L26)

**Comment by fforres** [comment]
Yes, sorry, i meant:
I was looking into a some steps for the user to find his country iso code if he doesn't know it.
Something along the lines of:
`Not your country? We can help you with that`
`Choose your Area/Continent` -> South America

```
Choose your country:
  - AR) - Argentina
  - CL) - Chile
  - CO) - Colombia
  - .... (And so on)
```

But i don't think inquierer is a good fit for displaying a list of 30 countries for you to choose yours :/

**Comment by martinheidegger** [comment]
Yes, `inquirer` doesn't have support for "completion". 

I chose [`iso3166-1`](https://npmjs.com/iso3166-1) because it contains less data than [`isoc`](https://www.npmjs.com/package/isoc). With `isoc` it would be easy to find out the name for a country:

```
require('isoc').reduce(function (all, item) { all[item.alpha2] = item.name.short; return all }, {})
```

**Comment by fforres** [comment]
Inquirer does support "bigger lists"
Working on something on this branch.  

https://github.com/nodeschool/admin/tree/bugfix/breaking-with-no-country-selected

The idea is to have a way for the user to choose his country besides the API suggestion.

Can be tested rejecting the Country proposal, and choosing `Latin America` as a continent

**Comment by fforres** [comment]
Tested again, admin failed because i was connected to a VPN.
Closing because I wasn't able to reproduce.
