### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by dinodsaurus** [nodeschool/admin#5]
I was thinking about adding tests to this cli tool. The question is should we go for mocha or tape? What are your preferences ?

**Comment by martinheidegger** [comment]
:sparkles: `'O'` :sparkles: I like `tape` better because it runs faster and I like `mocha` better because it produces nicer output. You can choose whatever you feel more comfortable with.

**Comment by martinheidegger** [comment]
@fforres What do you think?

**Comment by fforres** [comment]
I've been wanting to use tape some more :+1: 
I'm up for it :D

**Comment by martinheidegger** [comment]
`tape` it is! @dinodsaurus Do you mind to open a PR so we can collaborate on the tests?

**Comment by dinodsaurus** [comment]
Unfortunately I have started with mocha/chai :dancer: I will create a PR so you can check it out and if you dont like it we can rewrite it to tape :+1:

**Comment by fforres** [comment]
As long as we can Test @dinodsaurus.
I'm more familiar with the mocha/chai/sinon mix :) 

(Also, if you folks ever have the time, [AVA](https://github.com/sindresorhus/ava) sounds really cool, no globals though)

**Comment by martinheidegger** [comment]
AVA indeed looks interesting. For the time being plain-old mocha should suffice. I think this issue has been answered lets continue in #16
