### ISSUE TITLE
TimeZone for every event necessary?

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/admin#8]
Subtask for #6

Right now the [event specification](https://github.com/nodeschool/admin/commit/5005b39f1d211255e2796ed28118e9c3c1f3d068#diff-b5efc289e8ed207e5c8d8e5e76cf1004) asks for a `timeZone`. This is done mostly to make sure that the person entering the time is certain that he enters it in the correct time-zone. It could however be perfectly well be taken from lat/lng data.

I am sort of ambiguous on the current state and would love your input.

**Comment by lvivier** [comment]
Can't we sort of get around the timezone issue by requiring datetimes to be ISO8601? For interactive interfaces we can adjust based on local time if the timezone isn't given by the user.

**Comment by martinheidegger** [comment]
@lvivier I wanted to keep the tool as "optional" as possible. Theoretically one can perfectly well maintain a events json by themselves (even without linting). (← This might actually be an argument for making the timeZone optional).

Expanded: ISO8601 do usually not require a timezone but offer it and they are slightly hard to read: 
`1997-07-16T19:20:30.45+01:00` Also a "time only field" for the endtime is not allowed.

In the current `eventTime` module it allows for both `2000/01/01` as well as `1.1.2000` in the notation. Reason for this is again usability.

**Comment by martinheidegger** [comment]
@lvivier It might not look like but your question gave me quite a bit of clarity which is why I would like to continue the discussion here: https://github.com/nodeschool/admin/issues/9#issuecomment-173631332
