### ISSUE TITLE
TimeZone as IANA timezone or UTC+/-

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/admin#9]
Subtask for #6

The current timezone specification uses IANA timezones like `Asia/Tokyo`. Those timezones are imho. good to read for people. But they also contain the hidden issue that they are subject to change. I.e. the japanese government code get the crazy idea to change their timezone. (this happens on 1/2 countries during one year (average)). It might be more intelligent to change it to `UTC+09:00` or so to make it clear. This however brings on the problematic that the UTC timezones disregard Summer/Wintertime so the user will need to think in which timezone she is at the time of the event.

So I think we have 3 options:
1. Stay strict as it is now and require the `IANA` code
2. Make `IANA` optional and just take it from the `lat/lng`. Add information in the admin interface that it will use this lat/lng!
3. Change to `UTC+/-` codes which brings in Summer/Wintertime chaos.

I choose 1) because it seems best to me but am open for counter-arguments.

**Comment by fforres** [comment]
`IANA` works well, imo. :)
We could add a search/validation to prevent user errors, but adding the whole UTC/GMT/ETC seems too much chaos.

Although, considering the workshops are specific to a location/timezone, putting just a local time should work, for the purposes of the "event description"

**Comment by martinheidegger** [comment]
After further reflection: I think it would be best if the `timeZone`'s would be removed from the `events.json` entirely. The `lat/lng` location should provide sufficient information on the applicable timezone of the event. By adding the information to an event I am sure that it would just annoy people and it actually is duplicate information.

So, Instead of the current solution I would welcome PR that:
- removes the timeZone from the wizard and event specification 
- automatically evaluates and adds the timeZone to the output of `list`

**Comment by dinodsaurus** [comment]
Should we use this https://developers.google.com/maps/documentation/timezone/intro , or is there a better solution on doing this ?

**Comment by martinheidegger** [comment]
We are using [`tz-lookup`](https://www.npmjs.com/package/tz-lookup) for looking up the timezones [here](https://github.com/nodeschool/admin/blob/038e6098875506ca4eccc461677f9101e8a28cf6/lib/chapter/event-create.js#L204). It should be faster and less dependent than google.

**Comment by RichardLitt** [comment]
Would moment naturally fix this? Aren't there libraries which have solved this problem?

**Comment by martinheidegger** [comment]
I did Investigate quite a few options before using `tz-lookup` which is fast and light.

**Comment by RichardLitt** [comment]
Ok. I think [your comment](https://github.com/nodeschool/admin/issues/9#issuecomment-173631332) on removing timezones makes sense. Let's just do that.
